# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0014_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='soilMoisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilMoistureId', models.IntegerField(default=0)),
                ('soilMoistureName', models.CharField(default='Soil Moisture', max_length=100)),
                ('soilMoistureValue', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='plantId',
            field=models.IntegerField(default=0),
        ),
    ]
