# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0015_auto_20171121_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterBodyId', models.IntegerField(default=0)),
                ('waterBodyName', models.CharField(default='SriCity', max_length=100)),
                ('waterBodyVolume', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='weatherStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherStationName', models.CharField(default='SriCity', max_length=100)),
                ('weatherStationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.Sensors')),
            ],
        ),
        migrations.DeleteModel(
            name='soilMoisture',
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.Sensors'),
        ),
    ]
